// Uploads the site's static imagery to Cloudinary and writes the resulting
// URLs to a manifest the frontend imports.
//
// Usage (from backend/):
//   npm run upload-assets            # upload anything missing
//   npm run upload-assets -- --force # re-upload everything
//
// Idempotent: each file gets a deterministic public_id derived from its path,
// so re-running does not create duplicates and the URLs never change. That
// matters because those URLs end up committed in the manifest and stored on
// menu documents in the database.

import { v2 as cloudinary } from 'cloudinary';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const here = path.dirname(fileURLToPath(import.meta.url));
const SOURCE = path.resolve(here, '../../frontend/public/img');
const MANIFEST = path.resolve(here, '../../frontend/src/assets/cloudinary.js');
const FOLDER = 'bharadwaj-cafe/site';
const FORCE = process.argv.includes('--force');

const required = ['CLOUDINARY_CLOUD_NAME', 'CLOUDINARY_API_KEY', 'CLOUDINARY_API_SECRET'];
const missing = required.filter((key) => !process.env[key]);
if (missing.length) {
  console.error(`Missing ${missing.join(', ')} — set them in backend/.env`);
  process.exit(1);
}

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true,
});

/** `merch/tshirt.svg` -> `merch-tshirt`, so the id survives a folder rename. */
const publicIdFor = (relative: string): string =>
  relative
    .replace(/\.[^.]+$/, '')
    .replace(/[\\/]/g, '-')
    .toLowerCase();

/** `merch/tshirt.svg` -> `merchTshirt`, the manifest key. */
const keyFor = (relative: string): string =>
  publicIdFor(relative).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const walk = (dir: string, base = dir): string[] =>
  fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(full, base) : [path.relative(base, full)];
  });

const run = async (): Promise<void> => {
  if (!fs.existsSync(SOURCE)) {
    console.error(`No such directory: ${SOURCE}`);
    process.exit(1);
  }

  const files = walk(SOURCE).filter((f) => /\.(png|jpe?g|svg|webp|gif)$/i.test(f));
  console.log(`${files.length} images in ${SOURCE}\n`);

  const manifest: Record<string, string> = {};

  for (const relative of files) {
    const publicId = publicIdFor(relative);
    const fullId = `${FOLDER}/${publicId}`;

    if (!FORCE) {
      try {
        const existing = await cloudinary.api.resource(fullId);
        manifest[keyFor(relative)] = existing.secure_url as string;
        console.log(`  = ${relative.padEnd(34)} already uploaded`);
        continue;
      } catch {
        // Not there yet; fall through and upload it.
      }
    }

    const result = await cloudinary.uploader.upload(path.join(SOURCE, relative), {
      public_id: publicId,
      folder: FOLDER,
      overwrite: true,
      resource_type: 'image',
    });
    manifest[keyFor(relative)] = result.secure_url;
    console.log(`  + ${relative.padEnd(34)} ${(result.bytes / 1024).toFixed(0)} KB`);
  }

  const entries = Object.keys(manifest)
    .sort()
    .map((key) => `  ${key}: '${manifest[key]}',`)
    .join('\n');

  const contents = `/**
 * Cloudinary URLs for the site's static imagery.
 *
 * Generated by backend/scripts/uploadAssets.ts — run \`npm run upload-assets\`
 * in backend/ to regenerate. Do not edit by hand.
 *
 * The images are not in the repository and are not served by the app: a Vercel
 * deployment ships no image payload of its own, and Cloudinary handles format
 * negotiation and resizing. Public ids are derived from the original filenames,
 * so re-running the upload produces the same URLs rather than new ones.
 */

export const IMG = {
${entries}
};

/**
 * A menu document stores whatever URL the seeder or an admin upload gave it.
 * Older rows still hold relative paths like \`img/latte.png\` from before the
 * move; map those onto the manifest rather than letting them 404.
 */
export const resolveImage = (src) => {
  if (!src) return IMG.logo;
  if (/^https?:\\/\\//.test(src)) return src;
  const key = src
    .replace(/^\\/?img\\//, '')
    .replace(/\\.[^.]+$/, '')
    .replace(/[\\\\/]/g, '-')
    .toLowerCase()
    .replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  return IMG[key] ?? src;
};
`;

  fs.mkdirSync(path.dirname(MANIFEST), { recursive: true });
  fs.writeFileSync(MANIFEST, contents);
  console.log(`\nWrote ${Object.keys(manifest).length} URLs to ${MANIFEST}`);
};

run().catch((error: unknown) => {
  console.error('Upload failed:', error instanceof Error ? error.message : error);
  process.exit(1);
});
